### PR TITLE
Hotfix/old date for next aw

### PR DESCRIPTION
**Pull request by docNord**
Wrong date for next AW in the header is presumably what is causing it to end up in "past events" rather than "upcoming events". This should fix the issue.

### CODE REVIEW

**Review by mgcth — COMMENTED** [review]
Yeah, it is based on dates and time of build. Did you intend to add the access Sweden article as unpublished in this hotfix?

**Comment by docNord** [comment]
No, sorry about that. How can I best adress that?

**Comment by mgcth** [comment]
The easiest way would be to delete the file (save it locally), make a new commit and then squash all commits in this branch (git rebase -i ...) and force push.

**Comment by docNord** [comment]
Perhaps you could guide me after work today? I'd rather not mess up everything (again), and we are fast approaching the date of the thing :)

**Review by mgcth — APPROVED** [review]

**Pull request merged**
