### PR TITLE
Feature/site

### PR DESCRIPTION
**Pull request by mgcth**
**Description**

Add files and structure needed for [mysgen](https://github.com/mgcth/mysgen) to work. Also, add some dummy posts for now.

### CODE REVIEW

**Comment by mgcth** [comment]
I'll make an action for this, but locally this builds like this. Note that there isn't any style yet. Someone up for it?

Skärmavbild 2023-01-10 kl  23 26 59

**Comment by docNord** [comment]
@strobba has a style in place, couldn't we reuse that?

**Comment by mgcth** [comment]
> @strobba has a style in place, couldn't we reuse that?

Yeah, sounds good. I'll just clean up the template files. Site is deployed now at least.

**Comment by mgcth** [comment]
Ok, I think links sort of work now. We can probably merge this, and fix styling in another branch.

**Comment by mgcth** [comment]
Right now mysgen only looks for a `posts` and `pages` folder under `contents` and links are built based on that so our posts will be under `.../posts/...`. I can move this to `configs.json`, allowing a more Swedish naming.

I think we are done here. @strobba, did you want to add some colour to this?

**Review by strobba — APPROVED** [review]

**Pull request merged**
