### PR TITLE
Hotfix/aw post files

### PR DESCRIPTION
**Pull request by mgcth**
## Description

Add back proper url for missing files in AW posts.

### CODE REVIEW

**Comment by mgcth** [comment]
@docNord, I think this should fix it. Try it.

**Comment by mgcth** [comment]
Actually, I'm unsure if Swedish letters will work (filename on storage) in the url so let's just safe it like this.

**Comment by mgcth** [comment]
Actually, I'm a bit unsure about relative links now too. Too late for me to look into this now.

**Comment by docNord** [comment]
Waiting until tomorrow with the review, then.

**Comment by mgcth** [comment]
I think this will work.

**Review by docNord — APPROVED** [review]

**Pull request merged**
