### PR TITLE
Feature/add presentations 12/10 journalism aw

### PR DESCRIPTION
**Pull request by docNord**
- [x] Add Andreas' presentation
- [x] Add Annikas presentation

### CODE REVIEW

**Comment by docNord** [comment]
Should I also write a short news update about the seminar @mgcth ?

**Comment by mgcth** [comment]
Sounds like a good idea!

**Comment by docNord** [comment]
Alright, but approve this PR first so that we can make the material available, and I will write an article in a new PR, OK? @mgcth

**Review by mgcth — APPROVED** [review]

**Comment by mgcth** [comment]
@docNord, sorry. You forgot to add the metadata tag `data:`.

**Pull request merged**
